package lottery.random.generation.parameters;

/**
 * ParameterNumberOfGroups represents a parameter to an engine,
 * and represents the number of groups to be generated by
 * the engine.
 * 
 * @author Chris Adamson
 * @version 1.0
 */
public class ParameterNumberOfGroups 
extends Number {

	/**
	 * for serialization purposes. 
	 */
	private static final long serialVersionUID = 686431777521765940L;
	
	/**
	 * the number of groups with random numbers to generate. 
	 */
	private final Integer numberOfGroupsToGenerate;
	
	/**
	 * Constructs the parameter using the passed in Integer
	 * as the number of groups to be generated.
	 * 
	 * @param numberOfGroups the number of groups to generate
	 * @throws IllegalArgumentException if numberOfGroups is null.
	 */
	public ParameterNumberOfGroups(final Integer numberOfGroups) {
		
		// Sanity Check the argument.
		if (null == numberOfGroups) {
			throw new IllegalArgumentException("numberOfGroups can not be null");
		}
		
		this.numberOfGroupsToGenerate =
			numberOfGroups;
	}
	
	/**
	 * @see java.lang.Number#doubleValue()
	 */
	@Override
	public double doubleValue() {
		return numberOfGroupsToGenerate.doubleValue();
	}

	/**
	 * @see java.lang.Number#floatValue()
	 */
	@Override
	public float floatValue() {
		return numberOfGroupsToGenerate.floatValue();
	}

	/**
	 * @see java.lang.Number#intValue()
	 */
	@Override
	public int intValue() {
		return numberOfGroupsToGenerate.intValue();
	}

	/**
	 * @see java.lang.Number#longValue()
	 */
	@Override
	public long longValue() {
		return numberOfGroupsToGenerate.longValue();
	}
}
